namespace KH_Editor.Enums.DDD
{
    enum DDD_Pointers : long
    {
        MUNNY_MOD_EGS = 0xA4A05C,
        MUNNY_MOD_EGS_SIZE = 4,
        DROP_MOD_EGS_POINTER = 0xA94660,
        DROP_MOD_EGS_POINTER_SIZE = 8,
        DROP_MOD_EGS_POINTER_OFFSET = 434,
        DROP_MOD_EGS_SIZE = 1,

        INVENTORY_ITEMS_MOD_EGS = 0xA48904,
        INVENTORY_COMMANDS_MOD_EGS = 0xA48D74,

        BTLPARAM_MOD_EGS = 0x1098DDE0,
        ITEMDATA_MOD_EGS = 0x10982D30,

    }
}
